-- 病区表
DROP TABLE IF EXISTS ward;
CREATE TABLE ward (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ward_code VARCHAR(32) NOT NULL,
  ward_name VARCHAR(64) NOT NULL,
  bed_count INT NOT NULL DEFAULT 0,
  is_isolation TINYINT NOT NULL DEFAULT 0,
  max_accompany_per_bed INT NOT NULL DEFAULT 1,
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (ward_code)
);

-- 患者表
DROP TABLE IF EXISTS patient;
CREATE TABLE patient (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  patient_no VARCHAR(32) NOT NULL,
  patient_name VARCHAR(32) NOT NULL,
  id_card VARCHAR(18) NOT NULL,
  gender TINYINT NOT NULL DEFAULT 1,
  age INT DEFAULT NULL,
  ward_id BIGINT NOT NULL,
  bed_no VARCHAR(32) DEFAULT NULL,
  admission_date DATE NOT NULL,
  expected_discharge_date DATE DEFAULT NULL,
  diagnosis VARCHAR(255) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (patient_no)
);

-- 陪护人员表
DROP TABLE IF EXISTS accompany_person;
CREATE TABLE accompany_person (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  person_name VARCHAR(32) NOT NULL,
  id_card VARCHAR(18) NOT NULL,
  gender TINYINT NOT NULL DEFAULT 1,
  phone VARCHAR(11) NOT NULL,
  relation VARCHAR(32) NOT NULL,
  id_card_expire_date DATE NOT NULL,
  address VARCHAR(255) DEFAULT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (id_card)
);

-- 陪护申请表
DROP TABLE IF EXISTS accompany_apply;
CREATE TABLE accompany_apply (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  apply_no VARCHAR(32) NOT NULL,
  patient_id BIGINT NOT NULL,
  ward_id BIGINT NOT NULL,
  person_id BIGINT NOT NULL,
  apply_reason VARCHAR(255) DEFAULT NULL,
  expected_start_date DATE NOT NULL,
  expected_end_date DATE NOT NULL,
  apply_status TINYINT NOT NULL DEFAULT 0,
  audit_user_id BIGINT DEFAULT NULL,
  audit_user_name VARCHAR(32) DEFAULT NULL,
  audit_time TIMESTAMP DEFAULT NULL,
  audit_remark VARCHAR(255) DEFAULT NULL,
  invalid_reason VARCHAR(255) DEFAULT NULL,
  invalid_time TIMESTAMP DEFAULT NULL,
  apply_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (apply_no)
);

-- 陪护证表
DROP TABLE IF EXISTS accompany_certificate;
CREATE TABLE accompany_certificate (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cert_no VARCHAR(32) NOT NULL,
  apply_id BIGINT NOT NULL,
  patient_id BIGINT NOT NULL,
  ward_id BIGINT NOT NULL,
  person_id BIGINT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  cert_status TINYINT NOT NULL DEFAULT 1,
  issue_user_id BIGINT DEFAULT NULL,
  issue_user_name VARCHAR(32) DEFAULT NULL,
  issue_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  invalid_reason VARCHAR(255) DEFAULT NULL,
  invalid_time TIMESTAMP DEFAULT NULL,
  invalid_operator_id BIGINT DEFAULT NULL,
  invalid_operator_name VARCHAR(32) DEFAULT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (cert_no)
);

-- 门禁出入记录表
DROP TABLE IF EXISTS gate_record;
CREATE TABLE gate_record (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  record_no VARCHAR(32) NOT NULL,
  cert_id BIGINT NOT NULL,
  cert_no VARCHAR(32) NOT NULL,
  person_id BIGINT NOT NULL,
  person_name VARCHAR(32) NOT NULL,
  id_card VARCHAR(18) NOT NULL,
  ward_id BIGINT NOT NULL,
  ward_name VARCHAR(64) NOT NULL,
  gate_type TINYINT NOT NULL,
  check_result TINYINT NOT NULL,
  refuse_reason VARCHAR(255) DEFAULT NULL,
  gate_user_id BIGINT DEFAULT NULL,
  gate_user_name VARCHAR(32) DEFAULT NULL,
  check_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (record_no)
);

-- 系统用户表
DROP TABLE IF EXISTS sys_user;
CREATE TABLE sys_user (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(32) NOT NULL,
  real_name VARCHAR(32) NOT NULL,
  password VARCHAR(64) NOT NULL,
  role_type TINYINT NOT NULL,
  ward_id BIGINT DEFAULT NULL,
  phone VARCHAR(11) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (user_name)
);
