-- 病区表
DROP TABLE IF EXISTS ward;
CREATE TABLE ward (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ward_code VARCHAR(32) NOT NULL,
  ward_name VARCHAR(64) NOT NULL,
  bed_count INT NOT NULL DEFAULT 0,
  is_isolation TINYINT NOT NULL DEFAULT 0,
  max_accompany_per_bed INT NOT NULL DEFAULT 1,
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (ward_code)
);

-- 患者表
DROP TABLE IF EXISTS patient;
CREATE TABLE patient (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  patient_no VARCHAR(32) NOT NULL,
  patient_name VARCHAR(32) NOT NULL,
  id_card VARCHAR(18) NOT NULL,
  gender TINYINT NOT NULL DEFAULT 1,
  age INT DEFAULT NULL,
  ward_id BIGINT NOT NULL,
  bed_no VARCHAR(32) DEFAULT NULL,
  admission_date DATE NOT NULL,
  expected_discharge_date DATE DEFAULT NULL,
  diagnosis VARCHAR(255) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (patient_no)
);

-- 陪护人员表
DROP TABLE IF EXISTS accompany_person;
CREATE TABLE accompany_person (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  person_name VARCHAR(32) NOT NULL,
  id_card VARCHAR(18) NOT NULL,
  gender TINYINT NOT NULL DEFAULT 1,
  phone VARCHAR(11) NOT NULL,
  relation VARCHAR(32) NOT NULL,
  id_card_expire_date DATE NOT NULL,
  address VARCHAR(255) DEFAULT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (id_card)
);

-- 陪护申请表
DROP TABLE IF EXISTS accompany_apply;
CREATE TABLE accompany_apply (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  apply_no VARCHAR(32) NOT NULL,
  patient_id BIGINT NOT NULL,
  ward_id BIGINT NOT NULL,
  person_id BIGINT NOT NULL,
  apply_type TINYINT NOT NULL DEFAULT 1,
  source_cert_id BIGINT DEFAULT NULL,
  transfer_record_id BIGINT DEFAULT NULL,
  special_approval_id BIGINT DEFAULT NULL,
  apply_reason VARCHAR(255) DEFAULT NULL,
  expected_start_date DATE NOT NULL,
  expected_end_date DATE NOT NULL,
  apply_status TINYINT NOT NULL DEFAULT 0,
  audit_user_id BIGINT DEFAULT NULL,
  audit_user_name VARCHAR(32) DEFAULT NULL,
  audit_time TIMESTAMP DEFAULT NULL,
  audit_remark VARCHAR(255) DEFAULT NULL,
  invalid_reason VARCHAR(255) DEFAULT NULL,
  invalid_time TIMESTAMP DEFAULT NULL,
  apply_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (apply_no)
);

-- 陪护证表 - 扩展字段
DROP TABLE IF EXISTS accompany_certificate;
CREATE TABLE accompany_certificate (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cert_no VARCHAR(32) NOT NULL,
  apply_id BIGINT NOT NULL,
  patient_id BIGINT NOT NULL,
  ward_id BIGINT NOT NULL,
  person_id BIGINT NOT NULL,
  cert_type TINYINT NOT NULL DEFAULT 1,
  special_approval_id BIGINT DEFAULT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  cert_status TINYINT NOT NULL DEFAULT 1,
  current_leave_id BIGINT DEFAULT NULL,
  issue_user_id BIGINT DEFAULT NULL,
  issue_user_name VARCHAR(32) DEFAULT NULL,
  issue_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  invalid_reason VARCHAR(255) DEFAULT NULL,
  invalid_time TIMESTAMP DEFAULT NULL,
  invalid_operator_id BIGINT DEFAULT NULL,
  invalid_operator_name VARCHAR(32) DEFAULT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (cert_no)
);

-- 换陪护记录表
DROP TABLE IF EXISTS cert_transfer_record;
CREATE TABLE cert_transfer_record (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  transfer_no VARCHAR(32) NOT NULL,
  patient_id BIGINT NOT NULL,
  ward_id BIGINT NOT NULL,
  old_cert_id BIGINT DEFAULT NULL,
  old_cert_no VARCHAR(32) DEFAULT NULL,
  old_person_id BIGINT NOT NULL,
  old_person_name VARCHAR(32) NOT NULL,
  new_apply_id BIGINT DEFAULT NULL,
  new_cert_id BIGINT DEFAULT NULL,
  new_cert_no VARCHAR(32) DEFAULT NULL,
  new_person_id BIGINT NOT NULL,
  new_person_name VARCHAR(32) NOT NULL,
  handover_reason VARCHAR(500) NOT NULL,
  operator_id BIGINT DEFAULT NULL,
  operator_name VARCHAR(32) DEFAULT NULL,
  transfer_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  new_apply_status TINYINT NOT NULL DEFAULT 0,
  new_audit_user_id BIGINT DEFAULT NULL,
  new_audit_user_name VARCHAR(32) DEFAULT NULL,
  new_audit_time TIMESTAMP DEFAULT NULL,
  new_audit_remark VARCHAR(255) DEFAULT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (transfer_no)
);

-- 临时离院记录表
DROP TABLE IF EXISTS cert_leave_record;
CREATE TABLE cert_leave_record (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  leave_no VARCHAR(32) NOT NULL,
  cert_id BIGINT NOT NULL,
  cert_no VARCHAR(32) NOT NULL,
  patient_id BIGINT NOT NULL,
  ward_id BIGINT NOT NULL,
  person_id BIGINT NOT NULL,
  person_name VARCHAR(32) NOT NULL,
  leave_type TINYINT NOT NULL DEFAULT 1,
  leave_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expected_return_time TIMESTAMP DEFAULT NULL,
  actual_return_time TIMESTAMP DEFAULT NULL,
  leave_status TINYINT NOT NULL DEFAULT 1,
  invalid_reason VARCHAR(255) DEFAULT NULL,
  invalid_time TIMESTAMP DEFAULT NULL,
  operator_id BIGINT DEFAULT NULL,
  operator_name VARCHAR(32) DEFAULT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (leave_no)
);

-- 隔离病区特殊审批表
DROP TABLE IF EXISTS special_approval;
CREATE TABLE special_approval (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  approval_no VARCHAR(32) NOT NULL,
  patient_id BIGINT NOT NULL,
  patient_name VARCHAR(32) NOT NULL,
  ward_id BIGINT NOT NULL,
  ward_name VARCHAR(64) NOT NULL,
  person_id BIGINT NOT NULL,
  person_name VARCHAR(32) NOT NULL,
  id_card VARCHAR(18) NOT NULL,
  approval_reason VARCHAR(500) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  approval_status TINYINT NOT NULL DEFAULT 0,
  apply_user_id BIGINT DEFAULT NULL,
  apply_user_name VARCHAR(32) DEFAULT NULL,
  apply_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  audit_user_id BIGINT DEFAULT NULL,
  audit_user_name VARCHAR(32) DEFAULT NULL,
  audit_time TIMESTAMP DEFAULT NULL,
  audit_remark VARCHAR(255) DEFAULT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (approval_no)
);

-- 患者陪护配置表
DROP TABLE IF EXISTS ward_patient_config;
CREATE TABLE ward_patient_config (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  patient_name VARCHAR(32) NOT NULL,
  ward_id BIGINT NOT NULL,
  ward_name VARCHAR(64) NOT NULL,
  max_accompany_count INT NOT NULL DEFAULT 1,
  adjust_reason VARCHAR(500) DEFAULT NULL,
  operator_id BIGINT DEFAULT NULL,
  operator_name VARCHAR(32) DEFAULT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (patient_id)
);

-- 患者转病区记录表
DROP TABLE IF EXISTS patient_transfer_record;
CREATE TABLE patient_transfer_record (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  transfer_no VARCHAR(32) NOT NULL,
  patient_id BIGINT NOT NULL,
  patient_name VARCHAR(32) NOT NULL,
  from_ward_id BIGINT NOT NULL,
  from_ward_name VARCHAR(64) NOT NULL,
  from_bed_no VARCHAR(32) DEFAULT NULL,
  to_ward_id BIGINT NOT NULL,
  to_ward_name VARCHAR(64) NOT NULL,
  to_bed_no VARCHAR(32) DEFAULT NULL,
  operator_id BIGINT DEFAULT NULL,
  operator_name VARCHAR(32) DEFAULT NULL,
  transfer_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  remark VARCHAR(255) DEFAULT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (transfer_no)
);

-- 门禁出入记录表
DROP TABLE IF EXISTS gate_record;
CREATE TABLE gate_record (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  record_no VARCHAR(32) NOT NULL,
  cert_id BIGINT NOT NULL,
  cert_no VARCHAR(32) NOT NULL,
  person_id BIGINT NOT NULL,
  person_name VARCHAR(32) NOT NULL,
  id_card VARCHAR(18) NOT NULL,
  ward_id BIGINT NOT NULL,
  ward_name VARCHAR(64) NOT NULL,
  gate_type TINYINT NOT NULL,
  check_result TINYINT NOT NULL,
  refuse_reason VARCHAR(255) DEFAULT NULL,
  gate_user_id BIGINT DEFAULT NULL,
  gate_user_name VARCHAR(32) DEFAULT NULL,
  check_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (record_no)
);

-- 系统用户表
DROP TABLE IF EXISTS sys_user;
CREATE TABLE sys_user (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(32) NOT NULL,
  real_name VARCHAR(32) NOT NULL,
  password VARCHAR(64) NOT NULL,
  role_type TINYINT NOT NULL,
  ward_id BIGINT DEFAULT NULL,
  phone VARCHAR(11) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE (user_name)
);
